import 'bootstrap/dist/css/bootstrap.css'
import { Inter } from "next/font/google";
import "./globals.css";
import Bootsrapcomponent from './components/Bootsrapcomponent';
import { EdgeStoreProvider } from '../lib/edgestore';
import Navbar from './components/Navbar';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DonApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <Bootsrapcomponent/>
    <body className={inter.className}>
    {children}
    </body>
    </html>
  );
}